[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_tao = "G4eLua3cJfGkAkuYramavo2QjEwU37SUk6RJeW8U8bSW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/simonli/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
